name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for Creating Your First Issue in GitBook Our Mentors will review it soon'
        pr-message: 'Thanks for Creating Your First PR in GitBook Our Mentors will review it soon'
